# Enhanced Bug Bounty Assistant Configuration
openai:
  model: "gpt-3.5-turbo"  # More cost-effective
  temperature: 0.7
  max_tokens: 2000  # Reduced for token management
  timeout: 60
  batch_size: 25  # Reduced batch size
  rate_limit_delay: 2
  chunk_large_inputs: true

# Enhanced testing options
vulnerability_testing:
  modern_techniques: true
  mobile_testing: true
  graphql_testing: true
  websocket_testing: true
  
# Target-specific settings
target_profiles:
  uber:
    specific_tests: true
    focus_endpoints:
      - /api/riders/
      - /api/drivers/
      - /api/payments/
      - /api/fare/
  
  coinbase:
    specific_tests: true
    focus_endpoints:
      - /api/v2/
      - /api/v3/
      - /graphql
      
  x:
    specific_tests: true
    focus_endpoints:
      - /api/1.1/
      - /api/2/
      - /graphql

# Performance optimization
performance:
  max_concurrent_requests: 5
  request_delay: 1.5
  smart_filtering: true
  
# Enhanced detection
detection:
  use_modern_payloads: true
  deep_analysis: true
  confidence_threshold: "medium"
