aggressive_testing:
  enabled: true
  max_evasion_attempts: 15
  waf_detection: true
api_testing:
  graphql_introspection: true
  idor_testing: true
  jwt_testing: true
javascript_analysis:
  ai_analysis_for_large_files: true
  enabled: true
  max_files_to_analyze: 20
openai:
  max_tokens: 4000
  model: gpt-4
  temperature: 0.7
rate_limiting:
  base_delay: 0.5
  enabled: true
scope_validation:
  enabled: false
tools:
  httpx: true
  subfinder: true
  use_all: true
